### ISSUE TITLE
clj-new templates are broken

### ISSUE THREAD

**Issue by ajoberstar** [clojurephant/clojurephant#117]
## Expected Behavior

```
$ clj -A:new gradle-clj-lib myname/mylib
```

Should result in a working project.

## Current Behavior

Instead gets the following exception:

```
Downloading: gradle-clj-lib/clj-template/maven-metadata.xml from https://repo.clojars.org/
Exception in thread "main" clojure.lang.ExceptionInfo: Could not load template, require of clj.new.gradle-clj-lib failed with: Could not locate clj/new/gradle_clj_lib__init.class or clj/new/gradle_clj_lib.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name. {}
        at clojure.core$ex_info.invokeStatic(core.clj:4739)
        at clojure.core$ex_info.invoke(core.clj:4739)
        at clj_new.helpers$resolve_remote_template.invokeStatic(helpers.clj:130)
        at clj_new.helpers$resolve_remote_template.invoke(helpers.clj:35)
        at clj_new.helpers$resolve_template$fn__2432.invoke(helpers.clj:152)
        at clj_new.helpers$resolve_template.invokeStatic(helpers.clj:149)
        at clj_new.helpers$resolve_template.invoke(helpers.clj:145)
        at clj_new.helpers$create_STAR_.invokeStatic(helpers.clj:172)
        at clj_new.helpers$create_STAR_.invoke(helpers.clj:164)
        at clj_new.helpers$create.invokeStatic(helpers.clj:189)
        at clj_new.helpers$create.invoke(helpers.clj:176)
        at clj_new.create$_main.invokeStatic(create.clj:16)
        at clj_new.create$_main.doInvoke(create.clj:10)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.main$main_opt.invokeStatic(main.clj:317)
        at clojure.main$main_opt.invoke(main.clj:313)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
```

## Context

Prevents quick start from working.

## Steps to reproduce

See expected behavior.

## Environment

- **Build scan URL:**
- **gradle-clojure version:**
- **Gradle version:**
- **Java version:**
- **OS version:**

**Comment by tanelso2** [comment]
Same issue. It would be nice to have this fixed so I can easily introduce Clojure at work, where we are required to use gradle

**Comment by ajoberstar** [comment]
Finally... these are working again.
