### ISSUE TITLE
Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath

### ISSUE THREAD

**Issue by nabato** [clojurephant/clojurephant#218]
## Expected Behavior

`clojure/core__init.class` is on classpath.

## Current Behavior

build.gradle.kts
```kotlin
plugins {
    id("java")

    kotlin("jvm") version "1.9.10"

    id("dev.clojurephant.clojure") version "0.8.0-beta.7"
    
    id("org.jetbrains.intellij") version "1.16.0"

    id("org.jetbrains.changelog") version "2.0.0"

    id("org.jetbrains.qodana") version "0.1.13"

    id("org.jetbrains.kotlinx.kover") version "0.6.1"
}

group = properties("pluginGroup")
version = properties("pluginVersion")

// Configure project's dependencies
repositories {
    mavenCentral()
    maven {
        name = "Clojars"
        url = uri("https://repo.clojars.org")
    }
}


dependencies {
    implementation(kotlin("stdlib-jdk8"))

    implementation("org.clojure:clojure:1.12.0-alpha11")
}

clojure.builds.named("main") {
    checkAll()
    aotAll()
    reflection.set("fail")
}
```

gen-class
```clojure
(ns com.vlnabatov.alabaster.extensions.annotation.scalaannotator
  (:import (com.intellij.lang.annotation Annotator))
  (:gen-class
    :implements [com.intellij.lang.annotation.Annotator]
    :name com.vlnabatov.alabaster.extensions.annotation.CLJScalaAnnotator))

(defn annotate [this a b] (println "hello"))
```

`./gradlew runIde` output
```console
SEVERE - #c.i.o.u.KeyedExtensionCollector - Cannot create class com.vlnabatov.alabaster.extensions.annotation.CLJScalaAnnotator (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Alabaster Themes, id=com.vlnabatov.alabaster, descriptorPath=plugin.xml, path=~/projects/alabaster-themes/build/idea-sandbox/plugins/Alabaster Themes, version=1.0.83, package=null, isBundled=false), packagePrefix=null, state=active))
com.intellij.diagnostic.PluginException: Cannot create class com.vlnabatov.alabaster.extensions.annotation.CLJScalaAnnotator (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Alabaster Themes, id=com.vlnabatov.alabaster, descriptorPath=plugin.xml, path=~/projects/alabaster-themes/build/idea-sandbox/plugins/Alabaster Themes, version=1.0.83, package=null, isBundled=false), packagePrefix=null, state=active))
        at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:926)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:902)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:943)
        at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
        at com.intellij.serviceContainer.LazyExtensionInstance.getInstance(LazyExtensionInstance.java:44)
        at com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance(BaseKeyedLazyInstance.java:38)
        at com.intellij.openapi.util.KeyedExtensionCollector.instantiate(KeyedExtensionCollector.java:199)
        at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:161)
        at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:217)
        at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:142)
        at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:19)
        at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:111)
        at com.intellij.lang.LanguageExtension.collectAllForLanguage(LanguageExtension.java:125)
        at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:118)
        at com.intellij.lang.LanguageExtension.allForLanguageOrAny(LanguageExtension.java:146)
        at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.calcSupportedLanguages(AnnotatorRunner.java:100)
        at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotatorsAsync(AnnotatorRunner.java:66)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:328)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
        at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:417)
        at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:109)
        at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:412)
        at com.intellij.openapi.application.impl.RwLockHolder.tryRunReadAction(RwLockHolder.kt:310)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:403)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:402)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:378)
        at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:795)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:378)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:199)
        at com.intellij.openapi.application.impl.RwLockHolder.executeByImpatientReader(RwLockHolder.kt:491)
        at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:376)
        at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ExceptionInInitializerError
        at clojure.lang.Namespace.<init>(Namespace.java:37)
        at clojure.lang.Namespace.findOrCreate(Namespace.java:210)
        at clojure.lang.Var.internPrivate(Var.java:158)
        at com.vlnabatov.alabaster.extensions.annotation.CLJScalaAnnotator.<clinit>(Unknown Source)
        at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
        at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
        at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:908)
        at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:917)
        ... 46 more
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
        at clojure.lang.RT.load(RT.java:482)
        at clojure.lang.RT.load(RT.java:444)
        at clojure.lang.RT.<clinit>(RT.java:358)
        ... 54 more

```

## Context

Working on an [Intellij plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin).

## Steps to reproduce

`./gradlew runIde`

## Environment

- **Build scan URL: [scan](https://scans.gradle.com/s/orfa4rgig4q4s)**

P.S. Great and really helpful plugin you developed. Thank you.

**Comment by nabato** [comment]
Switching different java and gradle versions solved the issue. Java `22` and Gradle `8.4` worked for me.
