### ISSUE TITLE
Don't show stacktrace by default for compile errors

### ISSUE THREAD

**Issue by ajoberstar** [clojurephant/clojurephant#88]
## Expected Behavior (Bugs or Features)

Compile errors should be more concise if you aren't providing the `--stacktrace` flag. Often the error message from the Clojure compiler is good enough.

```
> Task :compileClojure
ERROR java.io.FileNotFoundException: Could not locate com/stuartsierra/component__init.class or com/stuartsierra/component.clj on classpath., compiling:(core.clj:1:1)

> Task :compileClojure FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileClojure'.
> Process 'command 'C:\Program Files\Zulu\zulu-10\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
2 actionable tasks: 2 executed
```

## Current Behavior (Bugs)

The full stack trace is always shown, see below.

```
> Task :compileClojure
ERROR java.io.FileNotFoundException: Could not locate com/stuartsierra/component__init.class or com/stuartsierra/component.clj on classpath., compiling:(core.clj:1:1)
Exception in thread "main" java.io.FileNotFoundException: Could not locate com/stuartsierra/component__init.class or com/stuartsierra/component.clj on classpath., compiling:(core.clj:1:1)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
        at clojure.lang.Compiler.compile1(Compiler.java:7609)
        at clojure.lang.Compiler.compile1(Compiler.java:7599)
        at clojure.lang.Compiler.compile(Compiler.java:7676)
        at clojure.lang.RT.compile(RT.java:413)
        at clojure.lang.RT.load(RT.java:458)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6627.invoke(core.clj:6061)
        at clojure.core$load.invokeStatic(core.clj:6060)
        at clojure.core$load.doInvoke(core.clj:6044)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5863)
        at clojure.core$compile$fn__6632.invoke(core.clj:6071)
        at clojure.core$compile.invokeStatic(core.clj:6071)
        at clojure.core$compile.invoke(core.clj:6063)
        at gradle_clojure.tools.clojure_compiler$_main$fn__184.invoke(clojure_compiler.clj:36)
        at gradle_clojure.tools.clojure_compiler$_main.invokeStatic(clojure_compiler.clj:29)
        at gradle_clojure.tools.clojure_compiler$_main.doInvoke(clojure_compiler.clj:26)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.main$main_opt.invokeStatic(main.clj:317)
        at clojure.main$main_opt.invoke(main.clj:313)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate com/stuartsierra/component__init.class or com/stuartsierra/component.clj on classpath.
        at clojure.lang.RT.load(RT.java:463)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6627.invoke(core.clj:6061)
        at clojure.core$load.invokeStatic(core.clj:6060)
        at clojure.core$load.doInvoke(core.clj:6044)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5863)
        at clojure.core$load_one.invoke(core.clj:5858)
        at clojure.core$load_lib$fn__6572.invoke(core.clj:5903)
        at clojure.core$load_lib.invokeStatic(core.clj:5902)
        at clojure.core$load_lib.doInvoke(core.clj:5883)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5940)
        at clojure.core$load_libs.doInvoke(core.clj:5924)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5962)
        at clojure.core$require.doInvoke(core.clj:5962)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at ranked_choice.core$loading__6513__auto____195.invoke(core.clj:1)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
        ... 29 more

> Task :compileClojure FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileClojure'.
> Process 'command 'C:\Program Files\Zulu\zulu-10\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
2 actionable tasks: 2 executed
```

## Context (Bugs and Features)

Since dropping the workers, the exceptions aren't as helpful. So we should do some work to generally not show exceptions and let them ask for the full one, if they need it. Maybe we can do something to pass the actual exception back, but not sure that's a good idea.

## Steps to reproduce (Bugs)

Create any Clojure compiler error and run the `classes` task.

## Environment (Bugs)

- **Build scan URL:**
- **gradle-clojure version:** 0.4.0-beta.6
- **Gradle version:** 4.8-rc-1
- **Java version:** 10
- **OS version:** Windows 10

**Comment by ajoberstar** [comment]
This was fixed in #158
